name: C/C++ CI

on:
  push:
    branches: [ "working_poll_no_timer" ]
  pull_request:
    branches: [ "working_poll_no_timer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: apt update && upgrade
      run: |
        sudo apt update

    - name: apt install valgrind
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install autotools-dev debhelper dpatch gdb libc6-dev gcc-multilib libc6-dbg

    - name: run unit tests
      run: make tester; make fclean
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asyncio

    - name: Test with connect clients
      run: |
        make; ./ircserv 6667 pw1234567 &
        python ./tests/conection_tests/tcpSocket.py
