name: C/C++ CI

on:
  push:
    branches: [ "working_poll_no_timer" ]
  pull_request:
    branches: [ "working_poll_no_timer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt install valgrind
      run: |
        sudo apt upgrade
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: run unit tests
      run: make tester; make fclean
