name: C/C++ CI

on:
  push:
    branches: [ "working_poll_no_timer" ]
  pull_request:
    branches: [ "working_poll_no_timer" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: apt update && upgrade install valgrind
      run: |
        sudo apt update
        sudo apt-get -y install valgrind
        sudo apt-get -y install autotools-dev debhelper dpatch gdb libc6-dev gcc-multilib libc6-dbg

    - name: run unit tests
      run: make tester; make fclean
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: install asyncio
      run: |
        python -m pip install --upgrade pip
        pip install asyncio

    - name: Test with connect clients
      run: |
        make; ./ircserv 6667 pw1234567 >/dev/null 2>&1 &
        python ./tests/conection_tests/tcpSocket.py
        python ./tests/conection_tests/basicTest.py